version: "3.7"
services:
  postgres_register:
    container_name: postgres-food-register
    image: postgres:12.2
    environment: 
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - "5432:5432"

  keycloak_food:
    container_name: keycloak_food
    image: jboss/keycloak:12.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"

  jaeger_food:
    container_name: jaeger_food
    image: jaegertracing/all-in-one:1.22
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
