version: "3.7"
services:
  postgres_register:
    container_name: postgres-food-register
    image: postgres:12.2
    environment: 
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - "5432:5432"

  keycloak_food:
    container_name: keycloack_food
    image: jboss/keycloak:12.0.4
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
